### ISSUE TITLE
Build error – LED_ON undeclared

### ISSUE THREAD

**Issue by JohnnytheRocket** [nicman23/dkms-hid-nintendo#21]
Following the README-instructions, the build-step gives a bad exit status: 2.

The log in
`/var/lib/dkms/nintendo/3.0/build/make.log`
states

```
DKMS make.log for nintendo-3.0 for kernel 4.9.140-tegra (aarch64)
mån 19 okt 2020 17:07:40 CEST
make: Entering directory '/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/kernel-4.9'
  CC [M]  /var/lib/dkms/nintendo/3.0/build/src/hid-nintendo.o
/var/lib/dkms/nintendo/3.0/build/src/hid-nintendo.c: In function ‘joycon_leds_create’:
/var/lib/dkms/nintendo/3.0/build/src/hid-nintendo.c:1782:46: error: ‘LED_ON’ undeclared (first use in this function); did you mean ‘LED_OFF’?
   led->brightness = ((i + 1) <= input_num) ? LED_ON : LED_OFF;
```

However, replacing `LED_ON` with `true` and `LED_OFF` with `false` on this and the following lines makes it build and install properly.

As the log-file states this was for a tegra device (Jetson Nano).

**Comment by nicman23** [comment]
too old a kernel. the nintendo switch and the switchroot project have a fork that works with nvidia's 4.9
